### ISSUE TITLE
docker-compose upでasstesファイルの変更が反映されない問題を解決

### ISSUE THREAD

**Issue by miloneko** [axsh/axsh_website_hugo#6]

**Comment by miloneko** [comment]
<img width="1170" alt="スクリーンショット 2023-02-14 17 39 36" src="https://user-images.githubusercontent.com/89956278/218683081-2251d3a2-cfee-4d86-ab6e-f38b8184eb86.png">
`docker-compose up'した時だけ、livereload' failedエラーになってCSSの変更が反映されない
## 試したこと

**Comment by miloneko** [comment]
## 実行したいこと
`docker-compose up`で、assetsファイルのcssの変更が反映されるようになること
## 出ているエラー
`hugo server -D`ではcssの変更が変更されるが、　`docker-compose up`では変更が反映されず、色が変わらず、
検証ツールのコンソールで
DevTools failed to load source map: Could not load content for http://localhost:1313/css/style.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILUREというエラーが出てる
## 考えられる原因
ドッカー内で実行されているhugoがボリュームマウントの静的ファイルの変更を認識できない？
liveReloadがdocker内で使えない(Dockerの外では使えているので）
## 試したこと
```
version: '3'
services: 
    hugo:
        image: klakegg/hugo:ubuntu
        volumes:
            - ".:/src"
        entrypoint: ["hugo", "server", "--poll", "700ms"]
        ports:
            - "1313:1313"
        tty: true
        working_dir: /src

```
entrypointに"--poll", "700ms"を追加した
→一時的に治ったが、また反映されなくなった

## 該当する場所
docker-compose.ymlファイル
theme/hugo-hero-theme
assets>scss>_bootstrap-variables.scss
20行目　$primary: #f19008;　⇦ここの色が全体のテーマカラーになっていて色の変更が確認できる

<img width="1918" alt="スクリーンショット 2023-02-15 12 50 50" src="https://user-images.githubusercontent.com/89956278/218924662-4e87c808-cd95-4ad7-a69f-d6333ca0a3c5.png">
